#!/usr/bin/env bash

# This command is the same as provided by the flake, except it runs "local" versions of all files

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
export MD_NIX="$(realpath "$SCRIPT_DIR/nix.md/md.nix")"
export CLI_SH="$(realpath "$SCRIPT_DIR/nix.md/cli.sh")"

bash "$CLI_SH" "$@"