#!/usr/bin/env bash

# runs the files in bootstrap instead of the files in the flake

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
export MARKDOWN_NIX="$(realpath "$SCRIPT_DIR/bootstrap/markdown.nix")"
export RUNTIME_NIX="$(realpath "$SCRIPT_DIR/bootstrap/runtime.nix")"
export NIXMD_SH="$(realpath "$SCRIPT_DIR/bootstrap/nixmd.sh")"

/usr/bin/env bash "$NIXMD_SH" "$@"
